env:
  node: true
  es2022: true
extends:
  - "eslint:recommended"
  - "plugin:import/recommended"
  - "prettier"
plugins:
  - import
parserOptions:
  ecmaVersion: 14
  sourceType: "module"
rules:
  "import/order":
    - error
    - newlines-between: always
  "import/extensions":
    - error
    - ignorePackages
    - js: always
  "quote-props":
    - error
    - consistent
