  env:
    node: true
    es2022: true
  extends: 
    - "eslint:recommended"
    - "plugin:import/recommended" 
    - "prettier"
  plugins: 
    - import
  parserOptions:
    ecmaVersion: "latest"
    sourceType: "module"
  ignorePatterns: ["src/utils/version.js"]
  rules:
    "import/order":
      - error
      - newlines-between: always